In [25]:
import numpy as np
import pandas as pd
import sys
sys.path.append('/Users/arthurzhou/github/aps360_project')
from src.data.data_utils import load_data, compare_single_fitness
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

### Comparing differences in experimental measures
Both single and continuous sets have fitness scores for single mutants. In some cases, the difference may be too large. We want to quantify these cases to check the quality of our data

### Load both processed datasets

In [36]:
root_ = '/Users/arthurzhou/github/aps360_project/src/data/raw/dms'
single_df = load_data(root_ +'/dms_single.xlsx', 'single')
double_df = load_data(root_ +'/dms_pair.xlsx','pair')

/Users/arthurzhou/miniconda3/envs/aps360/lib/python3.10/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

Data loaded. Prior size: 5741, After dropna: 5740
Data loaded. Prior size: 12374, After dropna: 12374

In [35]:
double_df

,Position of First Mut,Ambler Position,WT AA 1,WT AA 2,Mut AA 1,Mut AA 2,Mut 1 Fitness,Mut 1 Fitness Error,Mut 2 Fitness,Mut 2 Fitness Error,Double Mutant Fitness,Double Mutant Fitness Error,Epistasis,Upper Level Fractional Error,Lower Level Fractional Error,Positive Sign Epistasis,Negative Sign Epistasis,Unnamed: 17,Unnamed: 18
0,1,3,M,S,R,C,0.002063,0.000269,0.570203,0.084343,0.003714,0.000487,NaN,NaN,NaN,NaN,NaN,,NaN
1,1,3,M,S,I,R,0.416689,0.045892,0.689897,0.066357,0.007162,0.001334,-1.603535,-1.551035,-1.663265,NaN,NaN,NaN,NaN
2,1,3,M,S,T,G,0.063085,0.008628,0.417242,0.037710,0.010936,0.000721,-0.381459,-0.337224,-0.430717,NaN,NaN,NaN,NaN
3,1,3,M,S,I,G,0.416689,0.045892,0.417242,0.037710,0.011411,0.000447,-1.182876,-1.135091,-1.236577,NaN,NaN,NaN,NaN
4,1,3,M,S,I,T,0.416689,0.045892,1.139504,0.178914,0.059792,0.009567,-0.899889,-0.817011,-1.002403,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12369,285,289,H,W,W,G,NaN,NaN,0.006298,0.000497,0.003603,0.000191,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12370,285,289,H,W,E,A,0.839944,0.166490,NaN,NaN,0.001252,0.000204,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12371,285,289,H,W,R,A,0.931093,0.083061,NaN,NaN,0.001235,0.000096,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12372,285,289,H,W,A,A,0.649188,0.067464,NaN,NaN,0.000956,0.000086,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12373,285,289,H,W,L,A,0.660828,0.055656,NaN,NaN,0.000811,0.000137,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
single_double, stats, error_inter_indx_d, error_inter_indx_s = compare_single_fitness(single_df, double_df, 1)
stats

{'single_in_double': np.int64(9181),
 'single_in_double_ratio': np.float64(0.6908721498984122),
 'double_in_single': np.int64(10055),
 'double_in_single_ratio': np.float64(0.7566408307622846),
 'error_intersection': np.int64(10230),
 'error_intersection_ratio': np.float64(0.7698096169764467)}

In [57]:
double_df[~double_df.index.isin(error_inter_indx)]

,Position of First Mut,Ambler Position,WT AA 1,WT AA 2,Mut AA 1,Mut AA 2,Mut 1 Fitness,Mut 1 Fitness Error,Mut 2 Fitness,Mut 2 Fitness Error,Double Mutant Fitness,Double Mutant Fitness Error,Epistasis,Upper Level Fractional Error,Lower Level Fractional Error,Positive Sign Epistasis,Negative Sign Epistasis,Unnamed: 17,Unnamed: 18
0,1,3,M,S,R,C,0.002063,0.000269,0.570203,0.084343,0.003714,0.000487,NaN,NaN,NaN,NaN,NaN,,NaN
1,1,3,M,S,I,R,0.416689,0.045892,0.689897,0.066357,0.007162,0.001334,-1.603535,-1.551035,-1.663265,NaN,NaN,NaN,NaN
3,1,3,M,S,I,G,0.416689,0.045892,0.417242,0.037710,0.011411,0.000447,-1.182876,-1.135091,-1.236577,NaN,NaN,NaN,NaN
4,1,3,M,S,I,T,0.416689,0.045892,1.139504,0.178914,0.059792,0.009567,-0.899889,-0.817011,-1.002403,NaN,NaN,NaN,NaN
7,1,3,M,S,R,G,0.002063,0.000269,0.417242,0.037710,0.001839,0.000266,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12368,285,289,H,W,L,C,0.660828,0.055656,0.002603,0.000311,0.000837,0.000172,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12370,285,289,H,W,E,A,0.839944,0.166490,NaN,NaN,0.001252,0.000204,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12371,285,289,H,W,R,A,0.931093,0.083061,NaN,NaN,0.001235,0.000096,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12372,285,289,H,W,A,A,0.649188,0.067464,NaN,NaN,0.000956,0.000086,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12373,285,289,H,W,L,A,0.660828,0.055656,NaN,NaN,0.000811,0.000137,NaN,NaN,NaN,NaN,NaN,NaN,NaN